### ISSUE TITLE
Gutter SVG Path Wrong On Ace 1.3.3 With Ace-Diff 2.1.1

### ISSUE THREAD

**Issue by rholloway** [ace-diff/ace-diff#34]
I was originally using Ace 1.3.3 since it was recently released. However, I noticed that ace-diff 2.1.1 connectors/svg path don't seem to calculate correctly on this version of ace. All paths are placed at the very top of the gutter, so it's hard to match changes to left/right sides and vice versa.

Rolling back to ace 1.2.5 corrected the issue, so it seems to be related to version of ace and not other issues in setup.

Known issue?

**Comment by JackuB** [comment]
Do you have any screenshot or jsbin repro? Playing with 1.3.3 in jsbin I found no issues: https://jsbin.com/nefarok

**Comment by mengera88** [comment]
I have the same problem, have you solved this problem?@rholloway

**Comment by JackuB** [comment]
@mengera88 got a code sample? jsbin?

**Comment by mengera88** [comment]
@JackuB  Your jsbin example (https://jsbin.com/nefarok)has already  shown the problem. But when I use Ace 1.3.3, the problem is gone.  Besides, I recommend that you can add more parameters to set the line height of the editor. If the line height parameter is set later (after the Instantiation of the ace-diif), there will be problems with the position of the connection line. jsbin: https://jsbin.com/monorip/edit?html,output

**Comment by jeroenrinzema** [comment]
@JackuB screenshot of [jsbin](https://jsbin.com/nefarok) 
<img width="1440" alt="screen shot 2018-06-09 at 22 28 38" src="https://user-images.githubusercontent.com/3440116/41195803-9ac09084-6c34-11e8-89d9-cb8251b1c3e8.png">

**Comment by jeroenrinzema** [comment]
<img width="762" alt="screen shot 2018-06-09 at 22 30 12" src="https://user-images.githubusercontent.com/3440116/41195811-b4b283d0-6c34-11e8-81ab-d5ee16d5d5f7.png">

**Comment by nhan-ng** [comment]
I find the same problem only **on Google Chrome** 
ace: 1.3.3
ace-diff: ^2.1.2

using Firefox for the same setup doesn't show the problem.
